name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # or your required version

      - name: Restore dependencies
        run: dotnet restore ./GradeA.sln # <-- update this path

      - name: Build
        run: dotnet build ./GradeA.sln --configuration Release # <-- update this path

      - name: Test
        run: dotnet test ./GradeA.sln --no-build --verbosity normal # <-- update this path
